#!/bin/bash

# This script generates a .env file from environment variables.
# Useful for Jenkins pipelines to inject secrets securely.

# Moving to the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR"

ENV_FILE=".env"

echo "📝 Generating $ENV_FILE file..."

# Function to add variable to .env if it exists in environment
add_var() {
    local var_name=$1
    local display_name=${2:-$var_name}
    
    if [ ! -z "${!var_name}" ]; then
        echo "$var_name=${!var_name}" >> $ENV_FILE
        echo "✅ Added $display_name"
    else
        echo "⚠️  $var_name is not set in environment. Skipping."
    fi
}

# Clear or create .env file
> $ENV_FILE

echo "# Generated by Jenkins on $(date)" >> $ENV_FILE
echo "" >> $ENV_FILE

# Server Configuration
echo "# Server Configuration" >> $ENV_FILE
add_var "SERVER_PORT"
add_var "SERVER_HOST"

# Database Configuration
echo "" >> $ENV_FILE
echo "# Database Configuration" >> $ENV_FILE
add_var "DB_HOST"
add_var "DB_PORT"
add_var "DB_USER"
add_var "DB_PASSWORD" "DB_PASSWORD (hidden)"
add_var "DB_NAME"

# Redis Configuration
echo "" >> $ENV_FILE
echo "# Redis Configuration" >> $ENV_FILE
add_var "REDIS_HOST"
add_var "REDIS_PORT"
add_var "REDIS_PASSWORD" "REDIS_PASSWORD (hidden)"

echo "" >> $ENV_FILE
echo "✨ $ENV_FILE generation complete!"
chmod 600 $ENV_FILE
